spring:
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev
  application:
    name: mldncloud-config-client4              #定义微服务名称
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    instance-id: config-client.com
---
spring:
  profiles: product
  application:
    name: mldncloud-config-client4
server:
  port: 8102
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    instance-id: config-client.com
